### ISSUE TITLE
Regression in 0.51: UnexpectedError: undefined method name for #<Parser::Source::Map::Send:...>

### ISSUE THREAD

**Issue by myronmarston** [soutaro/steep#543]
As reported in #542, I got a bunch of logged internal errors when upgrading from 0.49 to 0.50. When I upgrade to 0.51, I get a bunch of additional type check errors that are like this:

```
elasticgraph-graphql/lib/elastic_graph/graphql/client.rb:10:4: [error] UnexpectedError: undefined method `name' for #<Parser::Source::Map::Send:0x00000001513c73a8>
│ Diagnostic ID: Ruby::UnexpectedError
│
└     class Client < Value.new(:source_description, :name)
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

These errors are present in 0.52.0 and 0.52.1 but first show up in 0.51.0.
