### ISSUE TITLE
Steep throws NoMethodError after upgrade to 1.9.1

### ISSUE THREAD

**Issue by aaronmallen** [soutaro/steep#1399]
```
╰─ bundle exec steep check                                                                                                                                                                                                                                                                                                                                                                                          ─╯
# Type checking files:

.2024-12-09 15:03:25.534: FATAL: [Steep 1.9.1] [typecheck:typecheck@6] [background] Unexpected error: #<NoMethodError: undefined method `encode_uri_component' for URI:Module

              href: "https://github.com/soutaro/steep/tree/v#{VERSION}/manual/ruby-diagnostics.md##{URI.encode_uri_component(diagnostic.diagnostic_code)}"
                                                                                                       ^^^^^^^^^^^^^^^^^^^^^
Did you mean?  encode_www_form_component>
2024-12-09 15:03:25.534: ERROR: [Steep 1.9.1] [typecheck:typecheck@6] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/diagnostic/lsp_formatter.rb:48:in `format'
2024-12-09 15:03:25.534: ERROR: [Steep 1.9.1] [typecheck:typecheck@6] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `block in handle_job'
2024-12-09 15:03:25.535: ERROR: [Steep 1.9.1] [typecheck:typecheck@6] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `each'
2024-12-09 15:03:25.535: ERROR: [Steep 1.9.1] [typecheck:typecheck@6] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `filter_map'
2024-12-09 15:03:25.535: ERROR: [Steep 1.9.1] [typecheck:typecheck@6] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `handle_job'
2024-12-09 15:03:25.535: ERROR: [Steep 1.9.1] [typecheck:typecheck@6] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
2024-12-09 15:03:25.535: ERROR: [Steep 1.9.1] [typecheck:typecheck@6] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `block in tagged'
2024-12-09 15:03:25.536: ERROR: [Steep 1.9.1] [typecheck:typecheck@6] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-09 15:03:25.536: ERROR: [Steep 1.9.1] [typecheck:typecheck@6] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `tagged'
2024-12-09 15:03:25.536: ERROR: [Steep 1.9.1] [typecheck:typecheck@6] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:46:in `block in run'
.2024-12-09 15:03:25.563: FATAL: [Steep 1.9.1] [typecheck:typecheck@11] [background] Unexpected error: #<NoMethodError: undefined method `encode_uri_component' for URI:Module

              href: "https://github.com/soutaro/steep/tree/v#{VERSION}/manual/ruby-diagnostics.md##{URI.encode_uri_component(diagnostic.diagnostic_code)}"
                                                                                                       ^^^^^^^^^^^^^^^^^^^^^
Did you mean?  encode_www_form_component>
2024-12-09 15:03:25.563: ERROR: [Steep 1.9.1] [typecheck:typecheck@11] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/diagnostic/lsp_formatter.rb:48:in `format'
2024-12-09 15:03:25.563: ERROR: [Steep 1.9.1] [typecheck:typecheck@11] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `block in handle_job'
2024-12-09 15:03:25.564: ERROR: [Steep 1.9.1] [typecheck:typecheck@11] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `each'
2024-12-09 15:03:25.569: ERROR: [Steep 1.9.1] [typecheck:typecheck@11] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `filter_map'
2024-12-09 15:03:25.569: ERROR: [Steep 1.9.1] [typecheck:typecheck@11] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `handle_job'
2024-12-09 15:03:25.569: ERROR: [Steep 1.9.1] [typecheck:typecheck@11] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
2024-12-09 15:03:25.569: ERROR: [Steep 1.9.1] [typecheck:typecheck@11] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `block in tagged'
2024-12-09 15:03:25.569: ERROR: [Steep 1.9.1] [typecheck:typecheck@11] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-09 15:03:25.570: ERROR: [Steep 1.9.1] [typecheck:typecheck@11] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `tagged'
2024-12-09 15:03:25.570: ERROR: [Steep 1.9.1] [typecheck:typecheck@11] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:46:in `block in run'
2024-12-09 15:03:25.586: FATAL: [Steep 1.9.1] [typecheck:typecheck@0] [background] Unexpected error: #<NoMethodError: undefined method `encode_uri_component' for URI:Module

              href: "https://github.com/soutaro/steep/tree/v#{VERSION}/manual/ruby-diagnostics.md##{URI.encode_uri_component(diagnostic.diagnostic_code)}"
                                                                                                       ^^^^^^^^^^^^^^^^^^^^^
Did you mean?  encode_www_form_component>
2024-12-09 15:03:25.586: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/diagnostic/lsp_formatter.rb:48:in `format'
2024-12-09 15:03:25.586: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `block in handle_job'
2024-12-09 15:03:25.586: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `each'
2024-12-09 15:03:25.586: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `filter_map'
2024-12-09 15:03:25.586: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `handle_job'
2024-12-09 15:03:25.604: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
2024-12-09 15:03:25.604: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `block in tagged'
2024-12-09 15:03:25.604: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-09 15:03:25.605: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `tagged'
2024-12-09 15:03:25.605: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:46:in `block in run'
.2024-12-09 15:03:25.627: FATAL: [Steep 1.9.1] [typecheck:typecheck@5] [background] Unexpected error: #<NoMethodError: undefined method `encode_uri_component' for URI:Module

              href: "https://github.com/soutaro/steep/tree/v#{VERSION}/manual/ruby-diagnostics.md##{URI.encode_uri_component(diagnostic.diagnostic_code)}"
                                                                                                       ^^^^^^^^^^^^^^^^^^^^^
Did you mean?  encode_www_form_component>
2024-12-09 15:03:25.627: ERROR: [Steep 1.9.1] [typecheck:typecheck@5] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/diagnostic/lsp_formatter.rb:48:in `format'
2024-12-09 15:03:25.627: ERROR: [Steep 1.9.1] [typecheck:typecheck@5] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `block in handle_job'
2024-12-09 15:03:25.627: ERROR: [Steep 1.9.1] [typecheck:typecheck@5] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `each'
..2024-12-09 15:03:25.634: ERROR: [Steep 1.9.1] [typecheck:typecheck@5] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `filter_map'
2024-12-09 15:03:25.634: ERROR: [Steep 1.9.1] [typecheck:typecheck@5] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `handle_job'
2024-12-09 15:03:25.634: ERROR: [Steep 1.9.1] [typecheck:typecheck@5] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
2024-12-09 15:03:25.635: ERROR: [Steep 1.9.1] [typecheck:typecheck@5] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `block in tagged'
2024-12-09 15:03:25.635: ERROR: [Steep 1.9.1] [typecheck:typecheck@5] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-09 15:03:25.635: ERROR: [Steep 1.9.1] [typecheck:typecheck@5] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `tagged'
2024-12-09 15:03:25.636: ERROR: [Steep 1.9.1] [typecheck:typecheck@5] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:46:in `block in run'
..2024-12-09 15:03:25.669: FATAL: [Steep 1.9.1] [typecheck:typecheck@0] [background] Unexpected error: #<NoMethodError: undefined method `encode_uri_component' for URI:Module

              href: "https://github.com/soutaro/steep/tree/v#{VERSION}/manual/ruby-diagnostics.md##{URI.encode_uri_component(diagnostic.diagnostic_code)}"
                                                                                                       ^^^^^^^^^^^^^^^^^^^^^
Did you mean?  encode_www_form_component>
2024-12-09 15:03:25.669: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/diagnostic/lsp_formatter.rb:48:in `format'
2024-12-09 15:03:25.669: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `block in handle_job'
2024-12-09 15:03:25.669: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `each'
2024-12-09 15:03:25.669: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `filter_map'
2024-12-09 15:03:25.669: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `handle_job'
2024-12-09 15:03:25.679: FATAL: [Steep 1.9.1] [typecheck:typecheck@4] [background] Unexpected error: #<NoMethodError: undefined method `encode_uri_component' for URI:Module

              href: "https://github.com/soutaro/steep/tree/v#{VERSION}/manual/ruby-diagnostics.md##{URI.encode_uri_component(diagnostic.diagnostic_code)}"
                                                                                                       ^^^^^^^^^^^^^^^^^^^^^
Did you mean?  encode_www_form_component>
2024-12-09 15:03:25.682: FATAL: [Steep 1.9.1] [typecheck:typecheck@3] [background] Unexpected error: #<NoMethodError: undefined method `encode_uri_component' for URI:Module

              href: "https://github.com/soutaro/steep/tree/v#{VERSION}/manual/ruby-diagnostics.md##{URI.encode_uri_component(diagnostic.diagnostic_code)}"
                                                                                                       ^^^^^^^^^^^^^^^^^^^^^
Did you mean?  encode_www_form_component>
2024-12-09 15:03:25.686: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
2024-12-09 15:03:25.686: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/diagnostic/lsp_formatter.rb:48:in `format'
2024-12-09 15:03:25.686: ERROR: [Steep 1.9.1] [typecheck:typecheck@3] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/diagnostic/lsp_formatter.rb:48:in `format'
2024-12-09 15:03:25.686: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `block in tagged'
2024-12-09 15:03:25.686: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `block in handle_job'
2024-12-09 15:03:25.686: ERROR: [Steep 1.9.1] [typecheck:typecheck@3] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `block in handle_job'
2024-12-09 15:03:25.686: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-09 15:03:25.686: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `each'
2024-12-09 15:03:25.686: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `tagged'
2024-12-09 15:03:25.686: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `filter_map'
2024-12-09 15:03:25.686: ERROR: [Steep 1.9.1] [typecheck:typecheck@3] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `each'
2024-12-09 15:03:25.686: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `handle_job'
2024-12-09 15:03:25.686: ERROR: [Steep 1.9.1] [typecheck:typecheck@0] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:46:in `block in run'
2024-12-09 15:03:25.687: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
2024-12-09 15:03:25.687: ERROR: [Steep 1.9.1] [typecheck:typecheck@3] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `filter_map'
2024-12-09 15:03:25.687: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `block in tagged'
2024-12-09 15:03:25.687: ERROR: [Steep 1.9.1] [typecheck:typecheck@3] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `handle_job'
2024-12-09 15:03:25.687: FATAL: [Steep 1.9.1] [typecheck:typecheck@7] [background] Unexpected error: #<NoMethodError: undefined method `encode_uri_component' for URI:Module

              href: "https://github.com/soutaro/steep/tree/v#{VERSION}/manual/ruby-diagnostics.md##{URI.encode_uri_component(diagnostic.diagnostic_code)}"
                                                                                                       ^^^^^^^^^^^^^^^^^^^^^
Did you mean?  encode_www_form_component>
2024-12-09 15:03:25.687: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-09 15:03:25.687: ERROR: [Steep 1.9.1] [typecheck:typecheck@3] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
2024-12-09 15:03:25.687: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `tagged'
2024-12-09 15:03:25.687: ERROR: [Steep 1.9.1] [typecheck:typecheck@7] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/diagnostic/lsp_formatter.rb:48:in `format'
2024-12-09 15:03:25.687: ERROR: [Steep 1.9.1] [typecheck:typecheck@3] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `block in tagged'
2024-12-09 15:03:25.687: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:46:in `block in run'
2024-12-09 15:03:25.687: ERROR: [Steep 1.9.1] [typecheck:typecheck@7] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `block in handle_job'
2024-12-09 15:03:25.687: ERROR: [Steep 1.9.1] [typecheck:typecheck@3] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-09 15:03:25.688: ERROR: [Steep 1.9.1] [typecheck:typecheck@7] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `each'
2024-12-09 15:03:25.688: ERROR: [Steep 1.9.1] [typecheck:typecheck@3] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `tagged'
2024-12-09 15:03:25.688: ERROR: [Steep 1.9.1] [typecheck:typecheck@7] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `filter_map'
2024-12-09 15:03:25.688: ERROR: [Steep 1.9.1] [typecheck:typecheck@3] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:46:in `block in run'
2024-12-09 15:03:25.688: ERROR: [Steep 1.9.1] [typecheck:typecheck@7] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `handle_job'
2024-12-09 15:03:25.688: ERROR: [Steep 1.9.1] [typecheck:typecheck@7] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
2024-12-09 15:03:25.688: ERROR: [Steep 1.9.1] [typecheck:typecheck@7] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `block in tagged'
2024-12-09 15:03:25.688: ERROR: [Steep 1.9.1] [typecheck:typecheck@7] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-09 15:03:25.688: ERROR: [Steep 1.9.1] [typecheck:typecheck@7] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `tagged'
2024-12-09 15:03:25.688: ERROR: [Steep 1.9.1] [typecheck:typecheck@7] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:46:in `block in run'
.....2024-12-09 15:03:25.788: FATAL: [Steep 1.9.1] [typecheck:typecheck@4] [background] Unexpected error: #<NoMethodError: undefined method `encode_uri_component' for URI:Module

              href: "https://github.com/soutaro/steep/tree/v#{VERSION}/manual/ruby-diagnostics.md##{URI.encode_uri_component(diagnostic.diagnostic_code)}"
                                                                                                       ^^^^^^^^^^^^^^^^^^^^^
Did you mean?  encode_www_form_component>
2024-12-09 15:03:25.788: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/diagnostic/lsp_formatter.rb:48:in `format'
2024-12-09 15:03:25.788: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `block in handle_job'
2024-12-09 15:03:25.788: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `each'
2024-12-09 15:03:25.788: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `filter_map'
2024-12-09 15:03:25.788: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/type_check_worker.rb:197:in `handle_job'
2024-12-09 15:03:25.798: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
2024-12-09 15:03:25.799: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `block in tagged'
2024-12-09 15:03:25.799: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-09 15:03:25.799: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.2.2/lib/active_support/tagged_logging.rb:138:in `tagged'
2024-12-09 15:03:25.799: ERROR: [Steep 1.9.1] [typecheck:typecheck@4] [background]   /Users/aaron/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/steep-1.9.1/lib/steep/server/base_worker.rb:46:in `block in run'
```

**Comment by tk0miya** [comment]
It seems `URI.encode_uri_component` was added since uri-v0.12 (bundled with ruby-3.1.4 or above).

refs:

* https://github.com/ruby/uri/pull/17
* https://github.com/ruby/ruby/pull/7261

Therefore it's better to upgrade the dependencies list.

**Comment by aaronmallen** [comment]
This was fixed for me by updating from ruby 3.1.0 to 3.1.6
